server:
  port: 8080
  deploy-version: 1.0.0
spring:
  profiles:
    group:
      default: clients
      test: clients-test
      staging: clients-staging
      prod: clients-prod
  mvc:
    static-path-pattern: /test/**
  main:
    banner-mode: off
  datasource:
    writer:
      hikari:
        jdbc-url: jdbc:mysql://localhost:33061/sharding?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
        username: sharding
        password: sharding
        pool-name: 'read-write-pool'
        driver-class-name: com.mysql.cj.jdbc.Driver
    reader:
      hikari:
        jdbc-url: jdbc:mysql://localhost:33061/sharding?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
        username: sharding
        password: sharding
        pool-name: 'read-pool'
        driver-class-name: com.mysql.cj.jdbc.Driver
        read-only: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:mysql://localhost:33061/sharding?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    user: sharding
    password: sharding
    locations: classpath:db/migration
logging:
  level:
    org.springframework.kafka.*: OFF
    org.springframework.kafka.listener.[KafkaMessageListenerContainer$ListenerConsumer]: OFF
    org.apache.kafka.*: OFF
    kafka.*: OFF
    org.apache.zookeeper.*: OFF
