spring:
  datasource:
    shards:
      shard-1:
        writer:
          minimum-idle: 0
          jdbc-url: jdbc:mysql://localhost:33061/sharding_test?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
          username: sharding
          password: sharding
          pool-name: 'shard-1-read-write-pool'
          driver-class-name: com.mysql.cj.jdbc.Driver
          read-only: false
        reader:
          minimum-idle: 0
          jdbc-url: jdbc:mysql://localhost:33062/sharding_test?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
          username: sharding
          password: sharding
          pool-name: 'shard-1-read-pool'
          driver-class-name: com.mysql.cj.jdbc.Driver
          read-only: true
      shard-2:
        writer:
          minimum-idle: 0
          jdbc-url: jdbc:mysql://localhost:33063/sharding_test?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
          username: sharding
          password: sharding
          pool-name: 'shard-2-read-write-pool'
          driver-class-name: com.mysql.cj.jdbc.Driver
          read-only: false
        reader:
          minimum-idle: 0
          jdbc-url: jdbc:mysql://localhost:33064/sharding_test?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
          username: sharding
          password: sharding
          pool-name: 'shard-2-read-pool'
          driver-class-name: com.mysql.cj.jdbc.Driver
          read-only: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: false
    baseline-on-migrate: true
    url: jdbc:mysql://localhost:33061/sharding_test?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    user: sharding
    password: sharding
    locations: classpath:db/migration
