version: '3.8'
services:
  mysql-shard-1-writer:
    image: mysql:8.0.33
    container_name: mysql-shard-1-writer
    restart: always
    ports:
      - '33061:3306'
    environment:
      MYSQL_USER: sharding
      MYSQL_PASSWORD: sharding
      MYSQL_DATABASE: sharding
      MYSQL_ROOT_PASSWORD: sharding
      TZ: 'Asia/Seoul'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-shard-1-writer-db:/var/lib/mysql
  mysql-shard-1-reader:
    image: mysql:8.0.33
    container_name: mysql-shard-1-reader
    restart: always
    ports:
      - '33062:3306'
    environment:
      MYSQL_USER: sharding
      MYSQL_PASSWORD: sharding
      MYSQL_DATABASE: sharding
      MYSQL_ROOT_PASSWORD: sharding
      TZ: 'Asia/Seoul'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-shard-1-reader-db:/var/lib/mysql
  mysql-shard-2-writer:
    image: mysql:8.0.33
    container_name: mysql-shard-2-writer
    restart: always
    ports:
      - '33063:3306'
    environment:
      MYSQL_USER: sharding
      MYSQL_PASSWORD: sharding
      MYSQL_DATABASE: sharding
      MYSQL_ROOT_PASSWORD: sharding
      TZ: 'Asia/Seoul'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-shard-2-writer-db:/var/lib/mysql
  mysql-shard-2-reader:
    image: mysql:8.0.33
    container_name: mysql-shard-2-reader
    restart: always
    ports:
      - '33064:3306'
    environment:
      MYSQL_USER: sharding
      MYSQL_PASSWORD: sharding
      MYSQL_DATABASE: sharding
      MYSQL_ROOT_PASSWORD: sharding
      TZ: 'Asia/Seoul'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-shard-2-reader-db:/var/lib/mysql
  mysql-shard-3-writer:
    image: mysql:8.0.33
    container_name: mysql-shard-3-writer
    restart: always
    ports:
      - '33065:3306'
    environment:
      MYSQL_USER: sharding
      MYSQL_PASSWORD: sharding
      MYSQL_DATABASE: sharding
      MYSQL_ROOT_PASSWORD: sharding
      TZ: 'Asia/Seoul'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-shard-3-writer-db:/var/lib/mysql
  mysql-shard-3-reader:
    image: mysql:8.0.33
    container_name: mysql-shard-3-reader
    restart: always
    ports:
      - '33066:3306'
    environment:
      MYSQL_USER: sharding
      MYSQL_PASSWORD: sharding
      MYSQL_DATABASE: sharding
      MYSQL_ROOT_PASSWORD: sharding
      TZ: 'Asia/Seoul'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-shard-3-reader-db:/var/lib/mysql

volumes:
  mysql-shard-1-writer-db:
  mysql-shard-1-reader-db:
  mysql-shard-2-writer-db:
  mysql-shard-2-reader-db:
  mysql-shard-3-writer-db:
  mysql-shard-3-reader-db:
